files:
  - { path: $(dirname)/autoware-main_gen2.yaml }

edits:
  - path: /sensing/autonomous_available
    type: remove

  - path: /hardware/autonomous_available
    type: remove

  - path: /foolproof/autonomous_available
    type: remove
