#!/usr/bin/env bash
# Collect upstream PR context for agent assessment.
#
# Usage:
#   gather-context.sh <upstream_pr_number> [--pr <downstream_pr>]

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

require_gh
require_jq

pr="${1:?usage: gather-context.sh <upstream_pr_number> [--pr <downstream_pr>]}"
shift || true
downstream_pr=""

while [[ $# -gt 0 ]]; do
    case "$1" in
    --pr)
        downstream_pr="$2"
        shift 2
        ;;
    *)
        echo "error: unknown argument $1" >&2
        exit 1
        ;;
    esac
done

root="$(repo_root)"
cd "$root"
git fetch origin "${TARGET_BRANCH}" >/dev/null 2>&1 || true

cache="$(pr_cache_dir "$pr")"
ensure_pr_cache_dir "$pr"
linked_dir="${cache}/linked-prs"
mkdir -p "$linked_dir"

"${SCRIPT_DIR}/fetch-upstream-pr.sh" "$pr"

gh pr view "$pr" --repo "${UPSTREAM_FULL}" --json body,title,labels,comments,reviews |
    jq -r '.body' >"${cache}/pr-body.md"

gh pr view "$pr" --repo "${UPSTREAM_FULL}" --json title,labels,comments,reviews \
    >"${cache}/pr-meta-full.json"

gh api "repos/${UPSTREAM_FULL}/pulls/${pr}/comments" --paginate 2>/dev/null |
    jq '[.[] | {path: .path, line: .line, body: .body, user: .user.login}]' \
        >"${cache}/pr-review-comments.json" || echo '[]' >"${cache}/pr-review-comments.json"

gh api "repos/${UPSTREAM_FULL}/issues/${pr}/comments" --paginate 2>/dev/null |
    jq '[.[] | {author: .user.login, body: .body, created_at: .created_at}]' \
        >"${cache}/pr-comments.json" || echo '[]' >"${cache}/pr-comments.json"

if [[ -n $downstream_pr ]]; then
    gh pr view "$downstream_pr" --repo "${DOWNSTREAM_FULL}" \
        --json number,title,body,labels,headRefName,url >"${cache}/downstream-pr.json" 2>/dev/null || true
fi

collect_text_sources() {
    jq -r '.title // empty' "${cache}/pr-meta-full.json" 2>/dev/null || true
    cat "${cache}/pr-body.md" 2>/dev/null || true
    jq -r '.[].message // empty' "${cache}/commits.json" 2>/dev/null || true
    jq -r '.[].body // empty' "${cache}/pr-comments.json" 2>/dev/null || true
}

extract_pr_refs_from_text() {
    local text_file="$1"
    grep -oE '(#[0-9]+|pull/[0-9]+|backport #?[0-9]+|\(#[0-9]+\))' "$text_file" 2>/dev/null |
        grep -oE '[0-9]+' || true
}

fetch_linked_pr() {
    local ref="$1"
    [[ $ref == "$pr" ]] && return 0
    local lcache="${linked_dir}/${ref}"
    mkdir -p "$lcache"
    [[ -f "${lcache}/meta.json" ]] && return 0
    if ! gh pr view "$ref" --repo "${UPSTREAM_FULL}" \
        --json number,title,body,url,mergedAt,files,commits >"${lcache}/meta.json" 2>/dev/null; then
        return 1
    fi
    jq -r '.body // ""' "${lcache}/meta.json" >"${lcache}/body.md"
    gh pr diff "$ref" --repo "${UPSTREAM_FULL}" >"${lcache}/diff.patch" 2>/dev/null || true
    echo "linked-pr: fetched #${ref}"
}

declare -A linked_set
while IFS= read -r ref; do
    [[ -z $ref ]] && continue
    linked_set["$ref"]=1
done < <(collect_text_sources | grep -oE '(#[0-9]+|pull/[0-9]+|backport #?[0-9]+)' | grep -oE '[0-9]+' | sort -nu)

pass2_refs=()
for ref in "${!linked_set[@]}"; do
    fetch_linked_pr "$ref" || true
done

for ref in "${!linked_set[@]}"; do
    body_file="${linked_dir}/${ref}/body.md"
    meta_file="${linked_dir}/${ref}/meta.json"
    [[ -f $body_file ]] || continue
    title="$(jq -r '.title // ""' "$meta_file" 2>/dev/null || true)"
    combined="${title}$(cat "$body_file")"
    while IFS= read -r ref2; do
        [[ -z $ref2 || $ref2 == "$pr" ]] && continue
        pass2_refs+=("$ref2")
    done < <(extract_pr_refs_from_text "$body_file" | sort -nu)
    if is_cherry_pick_pr_text "$combined"; then
        while IFS= read -r ref3; do
            [[ -z $ref3 || $ref3 == "$pr" ]] && continue
            pass2_refs+=("$ref3")
        done < <(extract_pr_refs_from_text "$body_file" | sort -nu)
    fi
done

for ref2 in "${pass2_refs[@]}"; do
    linked_set["$ref2"]=1
    fetch_linked_pr "$ref2" || true
done

linked_list=()
for ref in "${!linked_set[@]}"; do
    linked_list+=("$ref")
done
printf '%s\n' "${linked_list[@]}" | sort -nu | jq -R -s 'split("\n") | map(select(length>0)) | map(tonumber)' \
    >"${cache}/linked-prs.json"

{
    echo "# Upstream changed files (${UPSTREAM_FULL}#${pr})"
    echo ""
    jq -r '.[] | "- `\(.path)` (+\(.additions)/-\(.deletions))"' "${cache}/files.json"
} >"${cache}/changed-files.md"

worktree_note=""
if [[ -n $downstream_pr ]]; then
    wt="$(worktree_path "$downstream_pr")"
    if [[ -d $wt ]]; then
        echo "${wt}" >"${cache}/worktree-path.txt"
        worktree_note="${wt}"
    fi
fi

primary_title="$(jq -r '.title' "${cache}/meta.json")"
primary_url="$(jq -r '.url' "${cache}/meta.json")"

{
    echo "# Context bundle: ${UPSTREAM_FULL}#${pr}"
    echo ""
    echo 'Generated by `gather-context.sh`. Scripts do **not** map X2 paths to XX1.'
    echo "Use PR descriptions + [docs/xx1-x2-launch-knowledge-reference.md](../docs/xx1-x2-launch-knowledge-reference.md) §8, then **explore the worktree** for real layout and conflicts."
    echo ""
    echo "## Primary PR"
    echo "- **Title:** ${primary_title}"
    echo "- **URL:** ${primary_url}"
    echo "- **Body:** [pr-body.md](pr-body.md)"
    echo "- **Diff:** [diff.patch](diff.patch) ($(wc -l <"${cache}/diff.patch" | tr -d ' ') lines)"
    echo "- **Files:** $(jq -r '.[].path' "${cache}/files.json" | paste -sd, -)"
    echo ""
    if [[ -n $downstream_pr ]]; then
        echo "## Downstream cherry-pick PR #${downstream_pr}"
        jq -r '.body' "${cache}/downstream-pr.json" 2>/dev/null | head -40
        echo ""
    fi
    echo "## Linked / backport PRs"
    if [[ "$(jq 'length' "${cache}/linked-prs.json")" -eq 0 ]]; then
        echo "_None auto-detected — search body for backport references manually._"
    else
        jq -r '.[] | "- #\(.): '"${linked_dir}"'/\(.)/body.md"' "${cache}/linked-prs.json"
    fi
    echo ""
    echo "## Upstream file list"
    echo "See [changed-files.md](changed-files.md) (paths only; no XX1 mapping)."
    echo ""
    echo "## Explore the worktree (required before editing)"
    if [[ -n $worktree_note ]]; then
        echo "- **Path:** \`${worktree_note}\`"
        echo '- Compare upstream paths to this checkout: `find autoware_launch aip_launcher tier4_universe_launch -type f 2>/dev/null | head`'
        echo '- Grep for conflict markers: `git diff --name-only --diff-filter=U`'
        echo "- Cross-check §8 in the knowledge reference; do not rely on scripted rename rules."
    else
        echo '_Worktree not created yet — run `setup-worktree.sh` or `run-pr.sh` first, then re-read this bundle._'
    fi
    echo ""
    echo "## Agent assessment (required before resolving)"
    echo "Fill [agent-assessment.md](agent-assessment.md) using [assessment-template.md](../../assessment-template.md)."
    echo ""
    echo "## PR comment report (after resolution)"
    echo "Fill [pr-comment-report.md](pr-comment-report.md) using [comment-report-template.md](../../comment-report-template.md)."
    echo ""
    echo "## Suggested reading order"
    echo "1. pr-body.md + downstream PR body (downstream-pr.json)"
    echo "2. Linked PR bodies (especially cherry-pick originals)"
    echo "3. diff.patch + linked diffs + changed-files.md"
    echo "4. docs/xx1-x2-launch-knowledge-reference.md §8 (decision tree, skip list, rename checklist)"
    echo "5. Worktree tree/grep — confirm targets exist on XX1 before applying hunks"
} >"${cache}/context-bundle.md"

if [[ ! -f "${cache}/agent-assessment.md" ]]; then
    cp "${SKILL_ROOT}/assessment-template.md" "${cache}/agent-assessment.md"
fi

if [[ ! -f "${cache}/pr-comment-report.md" ]]; then
    cp "${SKILL_ROOT}/comment-report-template.md" "${cache}/pr-comment-report.md"
fi

echo "gather-context: ${cache}"
echo "  → Read: ${cache}/context-bundle.md"
echo "  → Fill: ${cache}/agent-assessment.md"
jq -r '.[] | "  linked PR: #\(.)"' "${cache}/linked-prs.json" 2>/dev/null || true
